#include <cassert>
#include <stdexcept>
int main(void)
{
    if(1 !=1)
    {
        throw std::runtime_error("h")e
    }
}
